services:
  integration-db:
    image: postgres
    env_file: ./server/.env
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  integration-redis:
    image: redis
    container_name: redis_cache

  integration-server:
    build: ./server
    env_file: ./server/.env
    command: npm run test
    restart: always
    depends_on:
      integration-db:
        condition: service_healthy

  integration-email:
    build: ./email
    command: npm run dev
    restart: always
    env_file: ./email/.env
